L'hyperplan affine de $\mathbb{R}^3$ donné par l'équation : 
$$ \mathcal{S} : \, x+y+z = 1 $$
est dirigé par les vecteurs $\mathbf{v}_1 = \begin{pmatrix} 1 \\ 0 \\ -1\end{pmatrix}$ et $\mathbf{v}_2 = \begin{pmatrix} 0 \\ 1 \\ -1\end{pmatrix}$. On pose la matrice $\mathbf{V} = [\mathbf{v}_1, \mathbf{v}_2]$ :
$$\mathbf{V} =  \begin{pmatrix} 1 & 0 \\ 0 & 1 \\ -1 & -1\end{pmatrix} $$

La matrice de projection sur la direction $\overrightarrow{\mathcal{S}}$ de $\mathcal{S}$ est donnée par $\mathbf{P} =\mathbf{V} \left(\mathbf{V}^T \mathbf{V} \right)^{-1}\mathbf{V}^T $  

In [1]:
import numpy as np

In [2]:
V = np.array([[1,0],[0,1],[-1,-1]])

In [3]:
P = V @ np.linalg.inv(V.T @ V) @ V.T

In [10]:
P

array([[ 0.66666667, -0.33333333, -0.33333333],
       [-0.33333333,  0.66666667, -0.33333333],
       [-0.33333333, -0.33333333,  0.66666667]])

Donc la matrice de projection
 $$\mathbf{P} = \dfrac{1}{3}\cdot\begin{pmatrix} 2 & -1 & -1 \\ -1 & 2 & -1 \\ -1 & -1 & 2\end{pmatrix} $$

In [8]:
p_1 = np.array([1,-2,4])
p_2 = np.array([1,0,4])

In [7]:
p_2

array([1, 4])

In [9]:
P @ p_2

array([-0.66666667, -1.66666667,  2.33333333])

In [13]:
V.T @ V

array([[2, 1],
       [1, 2]])

: 

In [ ]:

def generate_simplex_grid(n, resolution):
    # Initialiser la liste pour stocker les points du simplex
    simplex_points = []

    # Générer tous les points du simplex en utilisant une grille régulière
    for i in range(resolution + 1):
        for j in range(resolution - i + 1):
            # Calculer les coordonnées normalisées
            x = i / resolution
            y = j / resolution
            z = 1 - x - y if n == 3 else 0  # En dimension 3, la somme des coordonnées doit être 1

            # Ajouter le point au simplex si les coordonnées sont valides
            if x + y + z <= 1:
                simplex_points.append([x, y, z])

    return np.array(simplex_points)

# Exemple d'utilisation pour un simplex unité en dimension 2 avec une résolution de 10
n = 2
resolution = 10
simplex_grid = generate_simplex_grid(n, resolution)

# Afficher les points du simplex
print("Points du simplex unité en dimension", n, ":")
print(simplex_grid)
